services:
  - type: web
    name: portfolio-backend
    env: node
    branch: main
    plan: free
    region: oregon
    buildCommand: cd server && npm install
    startCommand: cd server && npm run start
    root: server

  - type: static
    name: portfolio-frontend
    env: static
    branch: main
    plan: free
    region: oregon
    buildCommand: cd client && npm install && npm run build
    publishPath: client/dist
    root: client
